server:
  port: 8082
      
spring:
  data:
    mongodb:
      host: localhost
      port: 27017            
      authentication-database: admin
      database: configuration
      username: admin
      password: password
  servlet:    
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB      

annotation:
  host: localhost
  port: 8081
    
storage:
  host: localhost
  port: 8083

security:
  host: localhost
  port: 8085

job:
  host: localhost
  port: 8084
  
---
server:
  port: 8082
     
spring:
  config:
    activate:
      on-profile: avib
  data:
    mongodb:
      host: avib-mongodb
      port: 27017
      authentication-database: admin
      database: configuration
      username: admin
      password: password   
  servlet:    
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB      

annotation:
  host: avib-backend-annotation
  port: 8081
          
storage:        
  host: avib-backend-storage
  port: 8083
  
security:
  host: avib-backend-security
  port: 8085
  
job:
  host: avib-backend-job
  port: 8084  