server:
  port: 8082

management:
  endpoint:
    health:
      probes:
        enabled: true
      
spring:
  data:
    mongodb:
      host: localhost
      port: 27017            
      authentication-database: admin
      database: configuration
      username: root
      password: q8SFbdesFv
  servlet:    
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB      

annotation:
  host: localhost
  port: 8081
    
storage:
  host: localhost
  port: 8083

security:
  host: localhost
  port: 8085

job:
  host: localhost
  port: 8084
  
---
server:
  port: 8082

management:
  endpoint:
    health:     
      probes:
        enabled: true
          
spring:
  config:
    activate:
      on-profile: avib
  data:
    mongodb:
      host: gsdpi-mongodb
      port: 27017
      authentication-database: admin
      database: configuration
      username: root
      password: 46cfdg1oXL   
  servlet:    
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB      

annotation:
  host: uniovi-avib-morphingprojections-backend-annotation
  port: 8081
          
storage:        
  host: uniovi-avib-morphingprojections-backend-storage
  port: 8083
  
security:
  host: uniovi-avib-morphingprojections-backend-security
  port: 8085
  
job:
  host: uniovi-avib-morphingprojections-backend-job
  port: 8084  