server:
  port: 8082

management:
  endpoint:
    health:
      probes:
        enabled: true
      
spring:
  data:
    mongodb:
      host: localhost
      port: 27017            
      authentication-database: admin
      database: configuration
      username: root
      password: password
      
  servlet:    
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB      

# using ingress
#spring:
#  elasticsearch:
#    host: minikube.io
#    port: 443
#    pathPrefix: /mongodb/
#    verifyHostnames: false
#    validateCertificates: false
#    authentication-database: admin    
#    database: configuration
#    username: root
#    password: password
  
storage:
  host: localhost
  port: 8083

security:
  host: localhost
  port: 8085
              
---
server:
  port: 8082

management:
  endpoint:
    health:     
      probes:
        enabled: true
          
spring:
  config:
    activate:
      on-profile: avib
      
  data:
    mongodb:
      host: avib-mongodb
      port: 27017
      authentication-database: admin
      database: configuration
      username: root
      password: password   
      
  servlet:    
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB      
        
storage:        
  host: uniovi-avib-morphingprojections-backend-storage
  port: 8083
  
security:
  host: uniovi-avib-morphingprojections-backend-security
  port: 8085